/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Q0TAvhiDOWl
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from "@/components/ui/collapsible"

export function Faqs() {
  return (
    <section className="w-full min-h-screen bg-[url('/faq-bg.svg')] bg-cover bg-center bg-no-repeat">
      <div className="container mx-auto px-4 py-20 md:py-32 lg:py-40">
        <div className="mx-auto max-w-3xl space-y-8 text-center">
          <h2 className="text-4xl font-bold tracking-tight md:text-5xl">FAQ</h2>
          <p className="text-muted-foreground md:text-xl">Frequently asked questions and answers about our product.</p>
        </div>
        <div className="mx-auto mt-12 max-w-3xl space-y-4">
          <Collapsible className="rounded-lg border bg-background/50 shadow-sm">
            <CollapsibleTrigger className="flex w-full items-center justify-between gap-4 px-6 py-4">
              <h3 className="text-lg font-medium">What is the pricing structure?</h3>
              <div className="h-5 w-5 transition-transform" />
            </CollapsibleTrigger>
            <CollapsibleContent className="px-6 pb-4">
              <p className="text-muted-foreground">
                We offer a range of pricing plans to suit different business needs. Our basic plan starts at $9 per
                month, with discounts available for annual subscriptions and larger teams.
              </p>
            </CollapsibleContent>
          </Collapsible>
          <Collapsible className="rounded-lg border bg-background/50 shadow-sm">
            <CollapsibleTrigger className="flex w-full items-center justify-between gap-4 px-6 py-4">
              <h3 className="text-lg font-medium">How do I get started with the product?</h3>
              <div className="h-5 w-5 transition-transform" />
            </CollapsibleTrigger>
            <CollapsibleContent className="px-6 pb-4">
              <p className="text-muted-foreground">
                Getting started is easy! Simply sign up for an account on our website and follow the step-by-step
                onboarding guide. Our support team is also available to help you get set up.
              </p>
            </CollapsibleContent>
          </Collapsible>
          <Collapsible className="rounded-lg border bg-background/50 shadow-sm">
            <CollapsibleTrigger className="flex w-full items-center justify-between gap-4 px-6 py-4">
              <h3 className="text-lg font-medium">What kind of support is available?</h3>
              <div className="h-5 w-5 transition-transform" />
            </CollapsibleTrigger>
            <CollapsibleContent className="px-6 pb-4">
              <p className="text-muted-foreground">
                We offer a range of support options, including email, live chat, and a comprehensive knowledge base. Our
                support team is available 24/7 to help you with any questions or issues you may have.
              </p>
            </CollapsibleContent>
          </Collapsible>
          <Collapsible className="rounded-lg border bg-background/50 shadow-sm">
            <CollapsibleTrigger className="flex w-full items-center justify-between gap-4 px-6 py-4">
              <h3 className="text-lg font-medium">Do you offer any integrations?</h3>
              <div className="h-5 w-5 transition-transform" />
            </CollapsibleTrigger>
            <CollapsibleContent className="px-6 pb-4">
              <p className="text-muted-foreground">
                Yes, we offer a wide range of integrations with popular third-party tools and platforms. This allows you
                to seamlessly connect our product with the tools you already use, streamlining your workflow.
              </p>
            </CollapsibleContent>
          </Collapsible>
          <Collapsible className="rounded-lg border bg-background/50 shadow-sm">
            <CollapsibleTrigger className="flex w-full items-center justify-between gap-4 px-6 py-4">
              <h3 className="text-lg font-medium">How secure is my data?</h3>
              <div className="h-5 w-5 transition-transform" />
            </CollapsibleTrigger>
            <CollapsibleContent className="px-6 pb-4">
              <p className="text-muted-foreground">
                We take data security very seriously. All of your data is encrypted both in transit and at rest, and we
                follow strict security protocols to ensure the protection of your information.
              </p>
            </CollapsibleContent>
          </Collapsible>
        </div>
      </div>
    </section>
  )
}
